{{- if .Values.rbac.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.rbac.secret.name }}
  namespace: {{ .Values.metadata.environment }}
  annotations:
    kubernetes.io/service-account.name: {{ .Values.rbac.secret.serviceAccountName }}
type: kubernetes.io/service-account-token
{{- end }}