metadata:
  environment: replace-me
  appName: replace-me

deployment:	
  create: false
  replicas: 1
  name: replace-me
  image: replace-me 
  ports: 
    - 8080
  resources:
    requests: 
      memory: "250Mi"
      cpu: "250m"
    limits: 
      memory: "350Mi"
      cpu: "300m"

networkPolicy:
  create: false
  open: true
  podSelector:
    matchLabels:
      app: replace-me   
  egress: {}
  ingress: {}

service:
  create: false
  ports: []
  # - name: mysql
  #   port: 3306
  #   targetPort: 3306

config:
  create: false